const animes=[
 {id:'jujutsu',title:'Jujutsu Kaisen',genres:['Acción','Fantasía'],studio:'MAPPA',score:'8.7',year:'2023',image:'images/jujutsu kaisen.jpeg',description:'Yuji Itadori se une a un grupo secreto de hechiceros para acabar con una maldición que lleva dentro.'},
 {id:'kimetsu',title:'Kimetsu no Yaiba',genres:['Acción','Fantasía'],studio:'ufotable',score:'8.7',year:'2024',image:'images/kimetsu.png',description:'Tanjiro emprende un viaje para devolver la humanidad a su hermana y derrotar a los demonios.'},
 {id:'hoshi',title:'Oshi no Ko',genres:['Drama','Romance'],studio:'Doga Kobo',score:'8.6',year:'2024',image:'images/hoshi no ko.jpg',description:'Una historia de luces, sombras y secretos en el corazón de la industria del entretenimiento.'},
 {id:'spy',title:'SPY × FAMILY',genres:['Comedia','Acción'],studio:'WIT Studio',score:'8.5',year:'2023',image:'images/spyxfamily.png',description:'Un espía, una asesina y una niña telépata forman la familia más peculiar de la ciudad.'},
 {id:'yourname',title:'Your Name',genres:['Romance','Fantasía'],studio:'CoMix Wave',score:'8.4',year:'2016',image:'images/kimi no nawa.png',description:'Dos adolescentes desconocidos intercambian cuerpos y descubren un lazo que supera el tiempo.'},
 {id:'sao',title:'Sword Art Online',genres:['Acción','Fantasía'],studio:'A-1 Pictures',score:'7.5',year:'2022',image:'images/sao.jpg',description:'Miles de jugadores quedan atrapados en un videojuego de realidad virtual donde perder significa todo.'},
 {id:'gotoubun',title:'The Quintessential Quintuplets',genres:['Romance','Comedia'],studio:'Bibury',score:'7.8',year:'2023',image:'images/go-hanayome.jpg',description:'Un tutor intenta ayudar a cinco hermanas idénticas a mejorar sus calificaciones y sus vidas.'},
 {id:'nogame',title:'No Game No Life',genres:['Fantasía','Comedia'],studio:'Madhouse',score:'8.1',year:'2014',image:'images/no game no life.png',description:'Dos hermanos invencibles en los juegos llegan a un mundo donde todo se decide jugando.'},
 {id:'naruto',title:'Naruto Shippuden',genres:['Acción','Fantasía'],studio:'Pierrot',score:'8.2',year:'2017',image:'images/naruto.png',description:'Naruto continúa su camino para proteger a sus amigos y convertirse en Hokage.'},
 {id:'totoro',title:'My Neighbor Totoro',genres:['Fantasía','Comedia'],studio:'Studio Ghibli',score:'8.1',year:'1988',image:'images/totoro.png',description:'Dos hermanas conocen a un espíritu amable del bosque tras mudarse al campo.'}
];
let favorites=JSON.parse(localStorage.getItem('nekostream-favorites')||'[]'),filter='Todos',query='';
const grid=document.querySelector('#anime-grid'),favGrid=document.querySelector('#favorites-grid'),count=document.querySelector('#result-count');
const isFavorite=id=>favorites.includes(id);
function card(a){return `<article class="anime-card"><button class="favorite ${isFavorite(a.id)?'saved':''}" data-favorite="${a.id}" aria-label="Guardar ${a.title}">${isFavorite(a.id)?'♥':'♡'}</button><button class="card-open" data-open="${a.id}" aria-label="Ver detalles de ${a.title}"><img src="${a.image}" alt="Póster de ${a.title}"><div class="card-gradient"></div><span class="card-rating">★ ${a.score}</span><div class="card-info"><h3>${a.title}</h3><p>${a.genres.join(' · ')} · ${a.year}</p></div></button></article>`}
function render(){const visible=animes.filter(a=>(filter==='Todos'||a.genres.includes(filter))&&(`${a.title} ${a.genres.join(' ')} ${a.studio}`).toLowerCase().includes(query));grid.innerHTML=visible.map(card).join('');count.textContent=`${visible.length} títulos`;document.querySelector('#empty-state').hidden=visible.length>0;renderFavorites()}
function renderFavorites(){const saved=animes.filter(a=>isFavorite(a.id));document.querySelector('#clear-list').hidden=!saved.length;if(!saved.length){favGrid.className='favorites-placeholder';favGrid.innerHTML='<span>♡</span><p>Aún no has guardado ningún anime.</p><small>Usa el corazón de una tarjeta para crear tu lista.</small>';return}favGrid.className='favorites-grid';favGrid.innerHTML=saved.map(a=>`<button class="favorite-mini" data-open="${a.id}"><img src="${a.image}" alt=""><strong>${a.title}</strong></button>`).join('')}
function toggleFavorite(id){favorites=isFavorite(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('nekostream-favorites',JSON.stringify(favorites));showToast(isFavorite(id)?'Añadido a Mi lista':'Eliminado de Mi lista');render()}
function openModal(id){const a=animes.find(x=>x.id===id);document.querySelector('#modal-content').innerHTML=`<div class="modal-body"><img src="${a.image}" alt="Póster de ${a.title}"><div class="modal-copy"><p class="eyebrow">${a.studio.toUpperCase()} · ${a.year}</p><h2>${a.title}</h2><span class="tags">★ ${a.score} · ${a.genres.join(' · ')}</span><p>${a.description}</p><button class="button button-primary" data-favorite="${a.id}">${isFavorite(a.id)?'♥ En mi lista':'♡ Añadir a mi lista'}</button></div></div>`;document.querySelector('#anime-modal').showModal()}
let toastTimer;function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
document.addEventListener('click',e=>{const fav=e.target.closest('[data-favorite]');if(fav){e.stopPropagation();toggleFavorite(fav.dataset.favorite);return}const open=e.target.closest('[data-open]');if(open)openModal(open.dataset.open)});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');filter=b.dataset.filter;render()}));
document.querySelector('#search-input').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();render()});
document.querySelector('#close-modal').addEventListener('click',()=>document.querySelector('#anime-modal').close());
document.querySelector('#trailer-button').addEventListener('click',()=>showToast('El avance estará disponible pronto.'));
document.querySelector('#theme-toggle').addEventListener('click',()=>{document.body.classList.toggle('light');showToast(document.body.classList.contains('light')?'Tema claro activado':'Tema oscuro activado')});
document.querySelector('#clear-list').addEventListener('click',()=>{favorites=[];localStorage.removeItem('nekostream-favorites');render();showToast('Mi lista se ha limpiado')});
render();
